import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Page configuration
st.set_page_config(
    page_title="AI Project Lead Qualifier",
    page_icon="🎯",
    layout="centered"
)

# Function to load the saved model
@st.cache_resource
def load_classification_model():
    try:
        # Loading the .pkl model generated by generate_full_project.py
        with open('lead_model.pkl', 'rb') as f:
            return pickle.load(f)
    except FileNotFoundError:
        return None

model = load_classification_model()

# Header Section
st.title("🎯 AI Project Lead Qualifier")
st.markdown("""
Classify incoming freelance leads as **High Quality** or **Low Quality** using our AI model trained with 99%+ accuracy.
""")

if model is None:
    st.error("⚠️ Model file 'lead_model.pkl' not found. Please run 'generate_full_project.py' first to train the model.")
else:
    # Sidebar Information
    st.sidebar.title("Model Insights")
    st.sidebar.info("""
    **Model:** Support Vector Machine (SVM)
    **Dataset:** 500 Instances
    **Target Accuracy:** 99%+
    """)

    # Main Input Form
    with st.form("qualifier_form"):
        st.subheader("Project Lead Details")
        
        col1, col2 = st.columns(2)
        
        with col1:
            budget = st.number_input(
                "Proposed Budget (USD)", 
                min_value=100, 
                max_value=50000, 
                value=3000,
                help="Total funds available for the project."
            )
            clarity = st.slider(
                "Technical Clarity (1-10)", 
                min_value=1, 
                max_value=10, 
                value=5,
                help="How clear are the project requirements?"
            )
            
        with col2:
            deadline = st.selectbox(
                "Has Fixed Deadline?", 
                options=[(1, "Yes"), (0, "No")], 
                format_func=lambda x: x[1],
                help="Is there a specific date the project must be finished by?"
            )
            words = st.number_input(
                "Initial Message Length", 
                min_value=5, 
                max_value=5000, 
                value=250,
                help="Total word count of the client's first message."
            )
            
        submit = st.form_submit_button("Analyze Lead", type="primary")

    # Prediction Result
    if submit:
        # Prepare input data matching the training features: 
        # budget_usd, tech_clarity_score, has_deadline, message_word_count
        features = np.array([[budget, clarity, deadline[0], words]])
        
        prediction = model.predict(features)[0]
        probabilities = model.predict_proba(features)[0]
        
        st.divider()
        
        if prediction == 1:
            st.success(f"### Result: HIGH QUALITY LEAD")
            st.write(f"**Confidence Score:** {probabilities[1]*100:.1f}%")
            st.balloons()
            st.info("✅ Recommendation: Priority follow-up. This lead matches your ideal client profile.")
        else:
            st.error(f"### Result: LOW QUALITY LEAD")
            st.write(f"**Confidence Score:** {probabilities[0]*100:.1f}%")
            st.warning("⚠️ Recommendation: Secondary priority. This lead may need more requirement gathering.")

# Footer
st.markdown("---")
st.caption("Powered by Scikit-Learn and Streamlit.")